apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
type: Opaque
data:
  GIT_SYNC_USERNAME: "YW5kZXJzb25lc2FudG8="
  GIT_SYNC_PASSWORD: "Z2hwX0JValRld1ZEc2hVeDZHektDQURURDRnRUxPYU11cTBYT3JObw=="

